#!/bin/sh

# genre: deep smooth jazz
# genre: smooth jazz
# genre: smooth saxophone


toukka-spotify-manager generate-playlist \
	--progress-bar \
	--expand-genre-to-playlists \
	--expand-genre-to-related-genres \
	--expand-playlist-to-items \
	--expand-track-to-album \
	--expand-album-to-tracks \
	--randomize-genres \
	--instrumental-only \
	--ignore-various-artists-albums \
	--ignore-played-albums \
	from-genres-re \
		".*smooth.(jazz|saxophone).*" \

