#!/bin/sh

#	--expand-track-to-recommendations \

toukka-spotify-manager generate-playlist \
	--progress-bar \
	--randomize-search \
	--expand-track-to-album \
	--expand-album-to-tracks \
	--expand-album-to-recommendations \
	--ignore-various-artists-albums \
	--instrumental-only \
		from-search album 'label:Signature Dark"'

