#!/bin/sh

#	--expand-track-to-recommendations \
#	--expand-album-to-recommendations \
#	--expand-track-to-album \

toukka-spotify-manager generate-playlist \
	--progress-bar \
	--expand-label-to-albums \
	--expand-album-to-tracks \
	--expand-album-to-artists \
	--expand-artist-to-random-album \
	--expand-artist-to-related-artists \
	--instrumental-only \
		from-labels "Jazz-O-Tech"

