#!/bin/sh

#	--ignore-various-artists-albums \
#	--randomize-artists \
#	--randomize-search \
#	--randomize-genres \

toukka-spotify-manager generate-playlist \
	--progress-bar \
	--expand-genre-to-artists \
	--expand-artist-to-albums \
	--expand-artist-to-related-artists \
	--expand-album-to-tracks \
	--instrumental-only \
	--ignore-played-albums \
	--ignore-classical-artists \
	--include-album-groups=album,single,compilation,appears_on \
	--ignore "spotify:artist:6lSQjYii4BRXZuFwmHJz5x" \
	from-genres-re \
		".*finnish.*jazz.*"

