#!/bin/sh

toukka-spotify-manager generate-playlist \
	--progress-bar \
	--expand-genre-to-playlists \
	--expand-genre-to-related-genres \
	--expand-track-to-album	\
	--expand-album-to-tracks \
	--randomize-artists \
	--randomize-search \
	--randomize-genres \
	--instrumental-only \
	--ignore-various-artists-albums \
	--ignore "genre:classical saxophone" \
	--ignore "genre:classical saxophone quartet" \
	from-genres-re \
		".*saxophone.*"


