#!/bin/sh

toukka-spotify-manager generate-playlist \
	--progress-bar \
	--expand-genre-to-artists \
	--expand-artist-to-random-album \
	--expand-artist-to-related-artists \
	--expand-album-to-tracks \
	--randomize-artists \
	--randomize-search \
	--randomize-genres \
	--instrumental-only \
	--ignore-played-albums \
	from-genres \
		"jazz piano" \
		"modern jazz piano"
