#!/bin/sh

toukka-spotify-manager generate-playlist \
        --progress-bar \
        --expand-genre-to-artists \
        --expand-artist-to-albums \
        --expand-artist-to-random-album \
        --expand-album-to-tracks \
        --expand-artist-to-related-artists \
        --randomize-genres \
        --randomize-artists \
        --randomize-search \
	--instrumental-only \
        --ignore-various-artists-albums \
        --ignore-played-albums \
	from-genres-re \
		".*jazztronica.*" \
		"nu jazz" \
		"acid jazz" \
		"electro jazz"


